WellCommerce\Bundle\AppBundle\Entity\Currency:
    type: entity
    table: currency
    repositoryClass: WellCommerce\Bundle\AppBundle\Repository\CurrencyRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 12
            unique: true
            nullable: false
