WellCommerce\Bundle\LocaleBundle\Entity\Locale:
    type: entity
    table: locale
    repositoryClass: WellCommerce\Bundle\LocaleBundle\Repository\LocaleRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 12
            unique: true
            nullable: false
