WellCommerce\Bundle\ReviewBundle\Entity\Review:
    type: entity
    table: review
    repositoryClass: WellCommerce\Bundle\ReviewBundle\Repository\ReviewRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nick:
            type: string
            nullable: false
        review:
            type: text
            nullable: false
        rating:
            type: integer
            nullable: false
        ratingLevel:
            type: integer
            nullable: false
        ratio:
            type: float
            nullable: false
        likes:
            type: integer
            nullable: false
        ratingRecommendation:
            type: integer
            nullable: false
        enabled:
            type: boolean
            nullable: false
    manyToOne:
        product:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\Product
            fetch: LAZY
            joinColumns:
                product_id:
                    referencedColumnName: id
                    onDelete: CASCADE
    oneToMany:
        reviewRecommendations:
            targetEntity: WellCommerce\Bundle\ReviewBundle\Entity\ReviewRecommendation
            cascade:
                - remove
                - persist
            fetch: EXTRA_LAZY
            mappedBy: review
            orphanRemoval: true
