# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\ReviewBundle\Entity\ReviewRecommendation:
    type: entity
    table: review_recommendation
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        liked:
            type: boolean
            nullable: false
        unliked:
            type: boolean
            nullable: false
    manyToOne:
        review:
            targetEntity: WellCommerce\Bundle\ReviewBundle\Entity\Review
            fetch: LAZY
            inversedBy: recommendations
            joinColumns:
                review_id:
                    referencedColumnName: id
                    onDelete: CASCADE
