WellCommerce\Bundle\AvailabilityBundle\Entity\Availability:
    fields:
        name:
            type: string
            length: 255
            nullable: false


WellCommerce\Bundle\AvailabilityBundle\Entity\AvailabilityTranslation:
    fields:
        type:
            type: string
            length: 255
            nullable: false
        type222:
            type: string
            length: 255
            nullable: false
