WellCommerce\Bundle\ProductBundle\Entity\Product:
    exclusion_policy: ALL
    xml_root_name: product
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
        createdAt:
            expose: true
            type: DateTime
        sku:
            expose: true
            type: string
        updatedAt:
            expose: true
            type: DateTime
