WellCommerce\Bundle\AttributeBundle\Entity\AttributeValue:
    type: entity
    table: attribute_value
    repositoryClass: WellCommerce\Bundle\AttributeBundle\Repository\AttributeValueRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        attribute:
            targetEntity: WellCommerce\Bundle\AttributeBundle\Entity\Attribute
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: values
            joinColumns:
                attribute_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    manyToMany:
        productAttributeValues:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\ProductAttribute
            cascade: {  }
            fetch: LAZY
            mappedBy: attributeValues
            inversedBy: null
            joinTable: {  }
            orderBy: null
    lifecycleCallbacks: {  }
