WellCommerce\Bundle\AttributeBundle\Entity\AttributeGroup:
    type: entity
    table: attribute_group
    repositoryClass: WellCommerce\Bundle\AttributeBundle\Repository\AttributeGroupRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    manyToMany:
        attributes:
            targetEntity: WellCommerce\Bundle\AttributeBundle\Entity\Attribute
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: groups
            joinTable:
                name: attribute_group_attribute
                schema: null
                joinColumns:
                    -
                        name: attribute_group_id
                        unique: false
                        nullable: true
                        onDelete: CASCADE
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: attribute_id
                        unique: false
                        nullable: true
                        onDelete: CASCADE
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
