WellCommerce\Bundle\AttributeBundle\Entity\AttributeValue:
    type: entity
    table: attribute_value
    repositoryClass: WellCommerce\Bundle\AttributeBundle\Repository\AttributeValueRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToMany:
        attributes:
            targetEntity: WellCommerce\Bundle\AttributeBundle\Entity\Attribute
            fetch: LAZY
            mappedBy: values
