WellCommerce\Bundle\AttributeBundle\Entity\AttributeGroup:
    type: entity
    table: attribute_group
    repositoryClass: WellCommerce\Bundle\AttributeBundle\Repository\AttributeGroupRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToMany:
        attributes:
            targetEntity: WellCommerce\Bundle\AttributeBundle\Entity\Attribute
            fetch: LAZY
            inversedBy: groups
            joinTable:
                name: attribute_group_attribute
                joinColumns:
                    -
                        name: attribute_group_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: attribute_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
