# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

imports:
    - { resource: "app/" }
    - { resource: "@WellCommerceCoreBundle/Resources/config/config.yml" }
    - { resource: "@WellCommerceAdminBundle/Resources/config/config.yml" }
    - { resource: "@WellCommerceApiBundle/Resources/config/config.yml" }
    - { resource: "@WellCommerceCatalogBundle/Resources/config/config.yml" }
    - { resource: "@WellCommerceClientBundle/Resources/config/config.yml" }
    - { resource: "@WellCommerceCmsBundle/Resources/config/config.yml" }
    - { resource: "@WellCommerceCouponBundle/Resources/config/config.yml" }
    - { resource: "@WellCommerceOrderBundle/Resources/config/config.yml" }
    - { resource: "@WellCommercePaymentBundle/Resources/config/config.yml" }
    - { resource: "@WellCommerceReportBundle/Resources/config/config.yml" }
    - { resource: "@WellCommerceReviewBundle/Resources/config/config.yml" }
    - { resource: "@WellCommerceShippingBundle/Resources/config/config.yml" }
    - { resource: "@WellCommerceShipmentBundle/Resources/config/config.yml" }
    - { resource: "@WellCommerceShowcaseBundle/Resources/config/config.yml" }
    - { resource: "@WellCommerceWishlistBundle/Resources/config/config.yml" }

parameters:
    number_formatter_locale: ~
    fixtures_load_order:
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadAdminMenuData: 0
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadThemeData: 10
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadCompanyData: 20
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadCurrencyData: 30
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadLocaleData: 40
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadOrderStatusGroupData: 41
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadOrderStatusData: 42
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadClientGroupData: 43
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadShopData: 50
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadUserData: 60
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadTaxData: 70
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadClientData: 90
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadUnitData: 110
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadContactData: 130
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadMediaData: 135
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadDelivererData: 140
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadAvailabilityData: 150
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadProducerData: 160
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadAttributeData: 170
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadCategoryData: 180
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadProductStatusData: 190
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadProductData: 200
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadShippingMethodData: 220
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadPaymentMethodData: 230
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadPageData: 240
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadNewsData: 250
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadSearchData: 260
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadReviewData: 270
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadShowcaseData: 280
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadLayeredNavigationData: 290
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadShowcaseData: 280
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadWishlistData: 280
    fixtures_product_limit: 100
    enabled_fixtures:
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadAdminMenuData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadThemeData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadCompanyData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadCurrencyData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadLocaleData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadOrderStatusGroupData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadOrderStatusData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadShopData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadUserData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadTaxData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadClientGroupData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadClientData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadUnitData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadContactData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadMediaData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadDelivererData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadAvailabilityData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadProducerData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadAttributeData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadCategoryData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadProductStatusData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadProductData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadShippingMethodData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadPaymentMethodData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadPageData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadNewsData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadSearchData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadReviewData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadShowcaseData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadLayeredNavigationData: true
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadWishlistData: true

well_commerce_api:
    request_handler:
        company:
            manager: company.manager
        currency:
            manager: currency.manager
        locale:
            manager: locale.manager
        media:
            manager: media.manager
        shop:
            manager: shop.manager
        tax:
            manager: tax.manager
    serialization:
        WellCommerce\Bundle\AppBundle\Entity\Company:
            mapping: "@WellCommerceAppBundle/Resources/config/serialization/Company.yml"
        WellCommerce\Bundle\AppBundle\Entity\CompanyAddress:
            mapping: "@WellCommerceAppBundle/Resources/config/serialization/CompanyAddress.yml"
        WellCommerce\Bundle\AppBundle\Entity\Currency:
            mapping: "@WellCommerceAppBundle/Resources/config/serialization/Currency.yml"
        WellCommerce\Bundle\AppBundle\Entity\CurrencyRate:
            mapping: "@WellCommerceAppBundle/Resources/config/serialization/CurrencyRate.yml"
        WellCommerce\Bundle\AppBundle\Entity\Locale:
            mapping: "@WellCommerceAppBundle/Resources/config/serialization/Locale.yml"
        WellCommerce\Bundle\AppBundle\Entity\Media:
            mapping: "@WellCommerceAppBundle/Resources/config/serialization/Media.yml"
        WellCommerce\Bundle\AppBundle\Entity\Shop:
            mapping: "@WellCommerceAppBundle/Resources/config/serialization/Shop.yml"
        WellCommerce\Bundle\AppBundle\Entity\Tax:
            mapping: "@WellCommerceAppBundle/Resources/config/serialization/Tax.yml"
        WellCommerce\Bundle\AppBundle\Entity\TaxTranslation:
            mapping: "@WellCommerceAppBundle/Resources/config/serialization/TaxTranslation.yml"

well_commerce_app:
    locale_copier:
        entities:
            WellCommerce\Bundle\AppBundle\Entity\DictionaryTranslation:
                properties:
                    - value
            WellCommerce\Bundle\AppBundle\Entity\LayoutBoxTranslation:
                properties:
                    - name
            WellCommerce\Bundle\AppBundle\Entity\TaxTranslation:
                properties:
                    - name

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../web/media/images"
    filter_sets:
        smallest:
            filters:
                thumbnail: { size: [60, 60], mode: outbound }
        small:
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
        normal:
            filters:
                thumbnail: { size: [175, 175], mode: outbound }
        medium:
            filters:
                thumbnail: { size: [240, 240], mode: outbound }
        large:
            filters:
                thumbnail: { size: [600, 600], mode: outbound }
        largest:
            filters:
                thumbnail: { size: [1200, 1200], mode: outbound }
        original:
            filters:
              strip: ~
