well_commerce_search:
    engine:
        adapters:
            elasticsearch:
                class: WellCommerce\Component\Search\Adapter\ElasticSearch\ElasticSearchAdapter
                options:
                    number_of_shards: 2
                    number_of_replicas: 0
                    index_prefix: wellcommerce_
                    query_min_length: 3
                    result_limit: 100
                    query_builder_class: WellCommerce\Component\Search\Adapter\ElasticSearch\ElasticSearchQueryBuilder
            lucene:
                class: WellCommerce\Component\Search\Adapter\ZendLucene\ZendLuceneAdapter
                options:
                    index_path: "%kernel.root_dir%/lucene"
                    max_buffered_docs: 10
                    max_merge_docs: 100000
                    merge_factor: 10
                    index_prefix: wellcommerce_
                    query_min_length: 3
                    result_limit: 100
                    query_builder_class: WellCommerce\Component\Search\Adapter\ZendLucene\ZendLuceneQueryBuilder

