well_commerce_review:
    configuration:
        review:
            orm:
                factory: WellCommerce\Bundle\ReviewBundle\Factory\ReviewFactory
                repository: WellCommerce\Bundle\ReviewBundle\Repository\ReviewRepository
                mapping: "@WellCommerceReviewBundle/Resources/config/doctrine/Review.orm.yml"
                entity: WellCommerce\Bundle\ReviewBundle\Entity\Review
            api:
                exposed: true
                dataset: review.dataset.admin
                manager: review.manager.admin
