wellcommerce_app:
    resource: "@WellCommerceAppBundle/Resources/config/routing.xml"

wellcommerce_attribute:
    resource: "@WellCommerceAttributeBundle/Resources/config/routing.xml"

wellcommerce_availability:
    resource: "@WellCommerceAvailabilityBundle/Resources/config/routing.xml"

wellcommerce_cart:
    resource: "@WellCommerceCartBundle/Resources/config/routing.xml"

wellcommerce_category:
    resource: "@WellCommerceCategoryBundle/Resources/config/routing.xml"

wellcommerce_contact:
    resource: "@WellCommerceContactBundle/Resources/config/routing.xml"

wellcommerce_currency:
    resource: "@WellCommerceCurrencyBundle/Resources/config/routing.xml"

wellcommerce_dictionary:
    resource: "@WellCommerceDictionaryBundle/Resources/config/routing.xml"

wellcommerce_layered_navigation:
    resource: "@WellCommerceLayeredNavigationBundle/Resources/config/routing.xml"

wellcommerce_layout:
    resource: "@WellCommerceLayoutBundle/Resources/config/routing.xml"

wellcommerce_locale:
    resource: "@WellCommerceLocaleBundle/Resources/config/routing.xml"

wellcommerce_shop:
    resource: "@WellCommerceShopBundle/Resources/config/routing.xml"

wellcommerce_company:
    resource: "@WellCommerceCompanyBundle/Resources/config/routing.xml"

wellcommerce_coupon:
    resource: "@WellCommerceCouponBundle/Resources/config/routing.xml"

wellcommerce_client:
    resource: "@WellCommerceClientBundle/Resources/config/routing.xml"

wellcommerce_deliverer:
    resource: "@WellCommerceDelivererBundle/Resources/config/routing.xml"

wellcommerce_media:
    resource: "@WellCommerceMediaBundle/Resources/config/routing.xml"

wellcommerce_news:
    resource: "@WellCommerceNewsBundle/Resources/config/routing.xml"

wellcommerce_admin:
    resource: "@WellCommerceAdminBundle/Resources/config/routing.xml"

wellcommerce_order:
    resource: "@WellCommerceOrderBundle/Resources/config/routing.xml"

wellcommerce_page:
    resource: "@WellCommercePageBundle/Resources/config/routing.xml"

wellcommerce_payment:
    resource: "@WellCommercePaymentBundle/Resources/config/routing.xml"

wellcommerce_producer:
    resource: "@WellCommerceProducerBundle/Resources/config/routing.xml"

wellcommerce_product:
    resource: "@WellCommerceProductBundle/Resources/config/routing.xml"

wellcommerce_product_status:
    resource: "@WellCommerceProductStatusBundle/Resources/config/routing.xml"

wellcommerce_report:
    resource: "@WellCommerceReportBundle/Resources/config/routing.xml"

wellcommerce_review:
    resource: "@WellCommerceReviewBundle/Resources/config/routing.xml"

wellcommerce_routing:
    resource: "@WellCommerceRoutingBundle/Resources/config/routing.xml"

wellcommerce_shipping:
    resource: "@WellCommerceShippingBundle/Resources/config/routing.xml"

wellcommerce_smuggler:
    resource: "@WellCommerceSmugglerBundle/Resources/config/routing.xml"

wellcommerce_tax:
    resource: "@WellCommerceTaxBundle/Resources/config/routing.xml"

wellcommerce_theme:
    resource: "@WellCommerceThemeBundle/Resources/config/routing.xml"

wellcommerce_unit:
    resource: "@WellCommerceUnitBundle/Resources/config/routing.xml"

wellcommerce_wishlist:
    resource: "@WellCommerceWishlistBundle/Resources/config/routing.xml"

root:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: admin.user.index
        permanent: false
