
services:
    search.layout_box.configurator:
        class: WellCommerce\Bundle\LayoutBundle\Configurator\SearchBoxConfigurator
        tags:
            - { name: layout_box.configurator }
        arguments: [Search, search.layout_box.controller, '@translator.helper']
        calls:
            - [setContainer, ['@service_container']]

    search.dataset.front:
        class: WellCommerce\Bundle\SearchBundle\DataSet\Front\SearchDataSet
        tags:
            - { name: dataset }
        arguments: ['@product.repository']
        calls:
            - [setRequestHelper, ['@request.helper']]
            - [setSearchManager, ['@search.manager.product']]

    search.controller.front:
        class: WellCommerce\Bundle\SearchBundle\Controller\Front\SearchController
        arguments: ['@product.manager']
        calls:
            - [setContainer, ['@service_container']]

    search.layout_box.controller:
        class: WellCommerce\Bundle\SearchBundle\Controller\Box\SearchBoxController
        arguments: ['@product.manager']
        calls:
            - [setContainer, ['@service_container']]

    search.command.reindex.products:
        class: WellCommerce\Bundle\SearchBundle\Command\ReindexProductsCommand
        tags:
            - { name: console.command }
