well_commerce_producer:
    services:
        producer:
            auto_services:
                factory: WellCommerce\Bundle\ProducerBundle\Factory\ProducerFactory
                repository: WellCommerce\Bundle\ProducerBundle\Repository\ProducerRepository
            orm_configuration:
                mapping: "@WellCommerceProducerBundle/Resources/config/doctrine/Producer.orm.yml"
                entity: WellCommerce\Bundle\ProducerBundle\Entity\Producer
        producer_route:
            auto_services:
                factory: ~
                repository: ~
            orm_configuration:
                mapping: "@WellCommerceProducerBundle/Resources/config/doctrine/ProducerRoute.orm.yml"
                entity: WellCommerce\Bundle\ProducerBundle\Entity\ProducerRoute
        producer_translation:
            auto_services:
                factory: ~
                repository: ~
            orm_configuration:
                mapping: "@WellCommerceProducerBundle/Resources/config/doctrine/ProducerTranslation.orm.yml"
                entity: WellCommerce\Bundle\ProducerBundle\Entity\ProducerTranslation
