services:
    breadcrumb.subscriber:
        class: WellCommerce\Bundle\CoreBundle\EventListener\BreadcrumbSubscriber
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [setContainer, ['@service_container']]

    breadcrumb.collection:
        class: WellCommerce\Component\Breadcrumb\Model\BreadcrumbCollection
        shared: false

    breadcrumb.provider:
        class: WellCommerce\Component\Breadcrumb\Provider\BreadcrumbProvider
        arguments: ['@breadcrumb.collection']

    twig.extension.breadcrumb:
        class: WellCommerce\Bundle\CoreBundle\Twig\Extension\BreadcrumbExtension
        tags:
            - { name: twig.extension }
        arguments: ['@breadcrumb.provider']
