services:
    datagrid.configurator:
        class: WellCommerce\Component\DataGrid\Configurator\DataGridConfigurator
        arguments: ['@event_dispatcher']

    twig.extension.datagrid:
        class: WellCommerce\Bundle\CoreBundle\Twig\Extension\DataGridExtension
        tags:
            - { name: twig.extension }
        arguments: ['WellCommerceCoreBundle:DataGrid:datagrid.html.twig']
