# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    theme.context.front:
        class: WellCommerce\Bundle\AppBundle\Context\Front\ThemeContext

    theme.locator:
        class: WellCommerce\Bundle\AppBundle\Locator\ThemeLocator
        arguments: ['@kernel', '@theme.context.front', '%fallback_theme%', '%kernel.root_dir%/../web/themes']

    theme.subscriber:
        class: WellCommerce\Bundle\AppBundle\EventListener\ThemeSubscriber
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [setContainer, ['@service_container']]

    theme.file_locator:
        class: WellCommerce\Bundle\AppBundle\Locator\FileLocator
        arguments: ['@theme.locator', ['%kernel.root_dir%/Resources']]

    theme.templating_locator:
        class: WellCommerce\Bundle\AppBundle\Locator\TemplateLocator
        arguments: ['@theme.file_locator', '%kernel.cache_dir%']

    theme.template_paths.cache_warmer:
        class: WellCommerce\Bundle\AppBundle\CacheWarmer\TemplatePathsCacheWarmer
        public: false
        arguments: ['@templating.finder', '@theme.templating_locator']
