tools:
    php_cpd:
        enabled: true
        excluded_dirs: {  }
        names:
            - '*.php'
        min_lines: 5
        min_tokens: 70
        filter:
            excluded_paths:
                - 'app/*'
                - 'tests/*'
                - 'bin/*'
            paths: {  }
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'app/*'
                - 'tests/*'
                - 'bin/*'
            paths: {  }
    php_analyzer:
        enabled: true
        config:
            metrics_coupling:
                enabled: true
                stable_code: { namespace_prefixes: {  }, classes: {  } }
            metrics_lack_of_cohesion_methods:
                enabled: true
            check_variables:
                enabled: true
            useless_function_calls:
                enabled: true
            suspicious_code:
                use_statement_alias_conflict: true
                precedence_in_condition_assignment: true
                parameter_multiple_times: true
                parameter_closure_use_conflict: true
                overriding_closure_use: true
                assignment_of_null_return: true
                enabled: true
                overriding_parameter: false
                non_existent_class_in_instanceof_check: true
                non_existent_class_in_catch_clause: true
                non_commented_switch_fallthrough: true
                non_commented_empty_catch_block: true
                overriding_private_members: true
                return_in_constructor: true
            dead_assignments:
                enabled: true
            unused_code:
                parameters: true
                methods: true
                enabled: true
            unreachable_code:
                enabled: true
            doctrine_parameter_binding:
                enabled: true
            precedence_checks:
                enabled: true
                assignment_in_condition: true
                comparison_of_bit_result: true
            basic_semantic_checks:
                property_on_interface: true
                missing_abstract_methods: true
                enabled: true
            deprecation_checks:
                enabled: true
        extensions:
            - php
        dependency_paths: {  }
        filter:
            excluded_paths:
                - 'app/*'
                - 'tests/*'
                - 'bin/*'
            paths: {  }
        path_configs: {  }
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            excluded_paths:
                - 'app/*'
                - 'tests/*'
                - 'bin/*'
            paths: {  }
    php_mess_detector:
        enabled: true
        config:
            code_size_rules:
                cyclomatic_complexity: false
                npath_complexity: false
                excessive_method_length: false
                excessive_class_length: false
                excessive_parameter_list: false
                excessive_public_count: false
                too_many_fields: false
                too_many_methods: false
                excessive_class_complexity: false
            design_rules:
                exit_expression: false
                eval_expression: false
                goto_statement: false
                number_of_class_children: false
                depth_of_inheritance: false
                coupling_between_objects: false
            unused_code_rules:
                unused_private_field: true
                unused_local_variable: false
                unused_private_method: false
                unused_formal_parameter: false
            naming_rules:
                constructor_conflict: false
                constant_naming: false
                boolean_method_name: false
            controversial_rules:
                superglobals: false
                camel_case_class_name: false
                camel_case_property_name: false
                camel_case_method_name: false
                camel_case_parameter_name: false
                camel_case_variable_name: false
            ruleset: null
        extensions:
            - php
        filter:
            excluded_paths:
                - 'app/*'
                - 'tests/*'
                - 'bin/*'
            paths: {  }
        path_configs: {  }
    sensiolabs_security_checker:
        enabled: true
        filter:
            excluded_paths:
                - 'app/*'
                - 'tests/*'
                - 'bin/*'
            paths: {  }
    php_code_sniffer:
        enabled: true
        config:
            sniffs:
                psr1: { classes: { class_declaration_sniff: false }, files: { side_effects_sniff: false } }
                generic: { code_analysis: { unused_function_parameter_sniff: false, for_loop_with_test_function_call_sniff: false, unconditional_if_statement_sniff: false, empty_statement_sniff: false, unnecessary_final_modifier_sniff: false, for_loop_should_be_while_loop_sniff: false, useless_overriding_method_sniff: true, jumbled_incrementer_sniff: true }, classes: { duplicate_class_name_sniff: false }, white_space: { disallow_tab_indent_sniff: false, disallow_space_indent_sniff: false }, php: { disallow_short_open_tag_sniff: false, sapi_usage_sniff: false, no_silenced_errors_sniff: false, deprecated_functions_sniff: false, upper_case_constant_sniff: false, closing_php_tag_sniff: false, forbidden_functions_sniff: false, lower_case_constant_sniff: false, character_before_php_opening_tag_sniff: false, lower_case_keyword_sniff: false }, formatting: { multiple_statement_alignment_sniff: false, no_space_after_cast_sniff: false, space_after_cast_sniff: false, disallow_multiple_statements_sniff: false }, functions: { function_call_argument_spacing_sniff: false, opening_function_brace_kernighan_ritchie_sniff: false, opening_function_brace_bsd_allman_sniff: false, call_time_pass_by_reference_sniff: false }, files: { one_interface_per_file_sniff: false, end_file_newline_sniff: false, inline_html_sniff: false, byte_order_mark_sniff: false, end_file_no_newline_sniff: false, one_class_per_file_sniff: false, line_endings_sniff: false }, version_control: { subversion_properties_sniff: false }, commenting: { fixme_sniff: false, todo_sniff: false }, control_structures: { inline_control_structure_sniff: false }, strings: { unnecessary_string_concat_sniff: false }, naming_conventions: { camel_caps_function_name_sniff: false, constructor_name_sniff: false, upper_case_constant_name_sniff: false }, metrics: { cyclomatic_complexity_sniff: false, nesting_level_sniff: false } }
                zend: { debug: { code_analyzer_sniff: false }, files: { closing_tag_sniff: false }, naming_conventions: { valid_variable_name_sniff: false } }
                squiz: { scope: { static_this_usage_sniff: false, method_scope_sniff: false, member_var_scope_sniff: false }, code_analysis: { empty_statement_sniff: false }, classes: { lowercase_class_keywords_sniff: false, valid_class_name_sniff: false, class_file_name_sniff: false, self_member_reference_sniff: false, class_declaration_sniff: false }, arrays: { array_bracket_spacing_sniff: false, array_declaration_sniff: false }, objects: { object_instantiation_sniff: false }, white_space: { logical_operator_spacing_sniff: false, language_construct_spacing_sniff: false, operator_spacing_sniff: false, control_structure_spacing_sniff: false, function_opening_brace_space_sniff: false, function_spacing_sniff: false, superfluous_whitespace_sniff: false, member_var_spacing_sniff: false, scope_closing_brace_sniff: false, scope_keyword_spacing_sniff: false, function_closing_brace_space_sniff: false, semicolon_spacing_sniff: false, cast_spacing_sniff: false, object_operator_spacing_sniff: false }, php: { disallow_comparison_assignment_sniff: false, disallow_size_functions_in_loops_sniff: false, heredoc_sniff: false, disallow_ob_end_flush_sniff: false, inner_functions_sniff: false, forbidden_functions_sniff: false, eval_sniff: false, lowercase_p_h_p_functions_sniff: false, discouraged_functions_sniff: false, embedded_php_sniff: false, commented_out_code_sniff: false, disallow_inline_if_sniff: false, disallow_multiple_assignments_sniff: false, global_keyword_sniff: false, non_executable_code_sniff: false }, formatting: { operator_bracket_sniff: false }, functions: { lowercase_function_keywords_sniff: false, global_function_sniff: false, function_duplicate_argument_sniff: false, multi_line_function_declaration_sniff: false, function_declaration_argument_spacing_sniff: false, function_declaration_sniff: false }, files: { file_extension_sniff: false }, commenting: { inline_comment_sniff: false, post_statement_comment_sniff: false, class_comment_sniff: false, doc_comment_alignment_sniff: false, block_comment_sniff: false, function_comment_sniff: false, function_comment_throw_tag_sniff: false, variable_comment_sniff: false, empty_catch_comment_sniff: false, file_comment_sniff: false, long_condition_closing_comment_sniff: false, closing_declaration_comment_sniff: false }, control_structures: { control_signature_sniff: false, lowercase_declaration_sniff: false, inline_if_declaration_sniff: false, for_each_loop_declaration_sniff: false, for_loop_declaration_sniff: false, switch_declaration_sniff: false, else_if_declaration_sniff: false }, strings: { echoed_strings_sniff: false, concatenation_spacing_sniff: false, double_quote_usage_sniff: false }, naming_conventions: { valid_function_name_sniff: false, valid_variable_name_sniff: false, constant_case_sniff: false }, operators: { increment_decrement_usage_sniff: false, valid_logical_operators_sniff: false, comparison_operator_usage_sniff: false } }
                my_source: { php: { return_function_value_sniff: false, eval_object_factory_sniff: false }, debug: { debug_code_sniff: false }, commenting: { function_comment_sniff: false } }
                psr2: { classes: { property_declaration_sniff: false, class_declaration_sniff: false }, methods: { method_declaration_sniff: false }, namespaces: { namespace_declaration_sniff: false, use_declaration_sniff: false }, files: { end_file_newline_sniff: false }, control_structures: { control_structure_spacing_sniff: false, switch_declaration_sniff: false, else_if_declaration_sniff: false } }
                pear: { classes: { class_declaration_sniff: false }, white_space: { object_operator_indent_sniff: false, scope_indent_sniff: false, scope_closing_brace_sniff: false }, formatting: { multi_line_assignment_sniff: false }, functions: { function_call_signature_sniff: false, function_declaration_sniff: false, valid_default_value_sniff: false }, files: { including_file_sniff: false }, commenting: { inline_comment_sniff: false, class_comment_sniff: false, function_comment_sniff: false, file_comment_sniff: false }, control_structures: { control_signature_sniff: false, multi_line_condition_sniff: false }, naming_conventions: { valid_function_name_sniff: false, valid_variable_name_sniff: false, valid_class_name_sniff: false } }
                wordpress: { arrays: { array_declaration_sniff: false }, classes: { valid_class_name_sniff: false }, files: { file_name_sniff: false }, formatting: { multiple_statement_alignment_sniff: false }, functions: { function_call_signature_sniff: false, function_declaration_argument_spacing_sniff: false }, naming_conventions: { valid_function_name_sniff: false }, objects: { object_instantiation_sniff: false }, php: { discouraged_functions_sniff: false }, strings: { double_quote_usage_sniff: false }, white_space: { control_structure_spacing_sniff: false, operator_spacing_sniff: false, php_indent_sniff: false }, xss: { escape_output_sniff: false } }
            ruleset: null
            standard: custom
            tab_width: 0
            encoding: utf8
        extensions:
            - php
        filter:
            excluded_paths:
                - 'app/*'
                - 'tests/*'
                - 'bin/*'
            paths: {  }
        path_configs: {  }
filter:
    excluded_paths:
        - 'app/*'
        - 'tests/*'
        - 'bin/*'
    paths: {  }
build_failure_conditions: {  }
_force_disabled: {  }
application:
    type: symfony2