language: php
php:
  - 5.5
  - 5.4
branches:
    only:
        - development
before_script:
    - composer self-update
    - composer update
    - curl http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar > selenium.jar
    - java -jar selenium.jar > /dev/null &

script:
    - vendor/bin/codecept run -c ./

notifications:
    email: "travis@wellcommerce.org"