WellCommerce\Bundle\CartBundle\Entity\Cart:
    type: entity
    table: cart
    repositoryClass: WellCommerce\Bundle\CartBundle\Repository\CartRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    embedded:
        totals:
            class: WellCommerce\Bundle\CartBundle\Entity\CartTotals
            columnPrefix: total_
        billingAddress:
            class: WellCommerce\Bundle\CoreBundle\Entity\Address
            columnPrefix: billing_address_
        shippingAddress:
            class: WellCommerce\Bundle\CoreBundle\Entity\Address
            columnPrefix: shipping_address_
        contactDetails:
            class: WellCommerce\Bundle\CoreBundle\Entity\ContactDetails
            columnPrefix: contact_details_
    fields:
        sessionId:
            type: string
            unique: true
            nullable: false
            column: session_id
    oneToMany:
        products:
            targetEntity: WellCommerce\Bundle\CartBundle\Entity\CartProduct
            cascade:
                - all
            fetch: LAZY
            mappedBy: cart
            orphanRemoval: true
    manyToOne:
        shop:
            targetEntity: WellCommerce\Bundle\MultiStoreBundle\Entity\Shop
            fetch: LAZY
            joinColumns:
                shop_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        shippingMethodCost:
            targetEntity: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethodCost
            fetch: LAZY
            joinColumns:
                shipping_method_cost_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        paymentMethod:
            targetEntity: WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethod
            fetch: LAZY
            joinColumns:
                payment_method_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
    oneToOne:
        client:
            targetEntity: WellCommerce\Bundle\ClientBundle\Entity\Client
            fetch: LAZY
            nullable: true
            joinColumns:
                client_id:
                    referencedColumnName: id
                    onDelete: CASCADE
