WellCommerce\Bundle\CartBundle\Entity\Cart:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: cart
    repositoryClass: WellCommerce\Bundle\CartBundle\Repository\CartRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    embedded:
        productTotal:
            class: WellCommerce\Bundle\OrderBundle\Entity\OrderProductTotalInterface
            columnPrefix: product_total_
        summary:
            class: WellCommerce\Bundle\OrderBundle\Entity\OrderSummaryInterface
            columnPrefix: summary_
        billingAddress:
            class: WellCommerce\Bundle\ClientBundle\Entity\ClientBillingAddress
            columnPrefix: billing_address_
        shippingAddress:
            class: WellCommerce\Bundle\ClientBundle\Entity\ClientShippingAddress
            columnPrefix: shipping_address_
        contactDetails:
            class: WellCommerce\Bundle\ClientBundle\Entity\ClientContactDetails
            columnPrefix: contact_details_
    fields:
        sessionId:
            type: string
            nullable: false
            column: session_id
        currency:
            type: string
            length: 16
            nullable: false
            column: currency
    oneToMany:
        products:
            targetEntity: WellCommerce\Bundle\CartBundle\Entity\CartProductInterface
            cascade:
                - all
            fetch: LAZY
            mappedBy: cart
            orphanRemoval: true
        modifiers:
            indexBy: name
            orderBy: { 'hierarchy': 'ASC' }
            targetEntity: WellCommerce\Bundle\CartBundle\Entity\CartModifierInterface
            cascade:
                - persist
            fetch: LAZY
            mappedBy: cart
            orphanRemoval: true
    manyToOne:
        coupon:
            targetEntity: WellCommerce\Bundle\CouponBundle\Entity\CouponInterface
            fetch: LAZY
            joinColumns:
                coupon_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        shop:
            targetEntity: WellCommerce\Bundle\ShopBundle\Entity\ShopInterface
            fetch: LAZY
            joinColumns:
                shop_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        shippingMethod:
            targetEntity: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethodInterface
            fetch: LAZY
            joinColumns:
                shipping_method_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        paymentMethod:
            targetEntity: WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethodInterface
            fetch: LAZY
            joinColumns:
                payment_method_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
    oneToOne:
        client:
            targetEntity: WellCommerce\Bundle\ClientBundle\Entity\ClientInterface
            fetch: LAZY
            nullable: true
            joinColumns:
                client_id:
                    referencedColumnName: id
                    onDelete: CASCADE
