well_commerce_page:
    services:
        page:
            auto_services:
                factory: WellCommerce\Bundle\PageBundle\Factory\PageFactory
                repository: WellCommerce\Bundle\PageBundle\Repository\PageRepository
            orm_configuration:
                mapping: "@WellCommercePageBundle/Resources/config/doctrine/Page.orm.yml"
                entity: WellCommerce\Bundle\PageBundle\Entity\Page
        page_route:
            auto_services:
                factory: ~
                repository: ~
            orm_configuration:
                mapping: "@WellCommercePageBundle/Resources/config/doctrine/PageRoute.orm.yml"
                entity: WellCommerce\Bundle\PageBundle\Entity\PageRoute
        page_translation:
            auto_services:
                factory: ~
                repository: ~
            orm_configuration:
                mapping: "@WellCommercePageBundle/Resources/config/doctrine/PageTranslation.orm.yml"
                entity: WellCommerce\Bundle\PageBundle\Entity\PageTranslation

    dynamic_routing:
        name: page
        class: WellCommerce\Bundle\PageBundle\Generator\PageRouteGenerator
        defaults:
            _controller: page.controller.front:indexAction
