WellCommerce\Bundle\ThemeBundle\Entity\Theme:
    type: entity
    table: theme
    repositoryClass: WellCommerce\Bundle\ThemeBundle\Repository\ThemeRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        folder:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
    oneToMany:
        css:
            targetEntity: WellCommerce\Bundle\ThemeBundle\Entity\ThemeCss
            cascade: {  }
            fetch: LAZY
            mappedBy: theme
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
