wellcommerce_app:
    resource: "@WellCommerceAppBundle/Resources/config/routing.xml"

wellcommerce_currency:
    resource: "@WellCommerceCurrencyBundle/Resources/config/routing.xml"

wellcommerce_locale:
    resource: "@WellCommerceLocaleBundle/Resources/config/routing.xml"

wellcommerce_shop:
    resource: "@WellCommerceShopBundle/Resources/config/routing.xml"

wellcommerce_company:
    resource: "@WellCommerceCompanyBundle/Resources/config/routing.xml"

wellcommerce_client:
    resource: "@WellCommerceClientBundle/Resources/config/routing.xml"

wellcommerce_user:
    resource: "@WellCommerceUserBundle/Resources/config/routing.xml"

wellcommerce_producer:
    resource: "@WellCommerceProducerBundle/Resources/config/routing.xml"

wellcommerce_product:
    resource: "@WellCommerceProductBundle/Resources/config/routing.xml"

wellcommerce_product_status:
    resource: "@WellCommerceProductStatusBundle/Resources/config/routing.xml"

wellcommerce_shipping:
    resource: "@WellCommerceShippingBundle/Resources/config/routing.xml"

wellcommerce_unit:
    resource: "@WellCommerceUnitBundle/Resources/config/routing.xml"

root:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: admin.user.index
        permanent: false
