# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

wellcommerce_api:
    resource: "@WellCommerceApiBundle/Resources/config/routing.yml"

wellcommerce_catalog:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing.yml"

wellcommerce_cms:
    resource: "@WellCommerceCmsBundle/Resources/config/routing.yml"

wellcommerce_core:
    resource: "@WellCommerceReviewBundle/Resources/config/routing.yml"

wellcommerce_currency:
    resource: "@WellCommerceCurrencyBundle/Resources/config/routing.yml"

wellcommerce_dictionary:
    resource: "@WellCommerceDictionaryBundle/Resources/config/routing.yml"

wellcommerce_distribution:
    resource: "@WellCommerceCoreBundle/Resources/config/routing.yml"

wellcommerce_layout:
    resource: "@WellCommerceLayoutBundle/Resources/config/routing.yml"

wellcommerce_locale:
    resource: "@WellCommerceLocaleBundle/Resources/config/routing.yml"

wellcommerce_shop:
    resource: "@WellCommerceShopBundle/Resources/config/routing.yml"

wellcommerce_company:
    resource: "@WellCommerceCompanyBundle/Resources/config/routing.yml"

wellcommerce_coupon:
    resource: "@WellCommerceCouponBundle/Resources/config/routing.yml"

wellcommerce_client:
    resource: "@WellCommerceClientBundle/Resources/config/routing.yml"

wellcommerce_media:
    resource: "@WellCommerceMediaBundle/Resources/config/routing.yml"

wellcommerce_admin:
    resource: "@WellCommerceAdminBundle/Resources/config/routing.yml"

wellcommerce_oauth:
    resource: "@WellCommerceOAuthBundle/Resources/config/routing.yml"

wellcommerce_order:
    resource: "@WellCommerceOrderBundle/Resources/config/routing.yml"

wellcommerce_payment:
    resource: "@WellCommercePaymentBundle/Resources/config/routing.yml"

wellcommerce_report:
    resource: "@WellCommerceReportBundle/Resources/config/routing.yml"

wellcommerce_routing:
    resource: "@WellCommerceCoreBundle/Resources/config/routing.yml"

wellcommerce_shipping:
    resource: "@WellCommerceShippingBundle/Resources/config/routing.yml"

wellcommerce_shipment:
    resource: "@WellCommerceShipmentBundle/Resources/config/routing.yml"

wellcommerce_tax:
    resource: "@WellCommerceTaxBundle/Resources/config/routing.yml"

wellcommerce_theme:
    resource: "@WellCommerceThemeBundle/Resources/config/routing.yml"

wellcommerce_wishlist:
    resource: "@WellCommerceWishlistBundle/Resources/config/routing.yml"

front.home_page.index:
    path: /
    defaults:
        _controller: 'web.home_page.controller.front:indexAction'

root:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: admin.user.index
        permanent: false

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: WellCommerceAppBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]
