WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethodCost:
    type: entity
    table: shipping_method_cost
    repositoryClass: WellCommerce\Bundle\ShippingBundle\Repository\ShippingMethodCostRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        rangeFrom:
            type: decimal
            scale: 4
            length: null
            unique: false
            nullable: false
            precision: 15
            column: range_from
        rangeTo:
            type: decimal
            scale: 4
            length: null
            unique: false
            nullable: false
            precision: 15
            column: range_to
        cost:
            type: decimal
            scale: 4
            length: null
            unique: false
            nullable: false
            precision: 15
    manyToOne:
        shippingMethod:
            targetEntity: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethod
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: costs
            joinColumns:
                shipping_method_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
