WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethod:
    type: entity
    table: shipping_method
    repositoryClass: WellCommerce\Bundle\ShippingBundle\Repository\ShippingMethodRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        calculator:
            type: string
            scale: 0
            length: 64
            unique: false
            nullable: true
            precision: 0
        currency:
            type: string
            scale: 0
            length: 16
            unique: false
            nullable: false
            precision: 0
        enabled:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        hierarchy:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            options:
                default: 0
    manyToOne:
        tax:
            targetEntity: WellCommerce\Bundle\TaxBundle\Entity\Tax
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tax_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
            orphanRemoval: false
    oneToMany:
        costs:
            targetEntity: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethodCost
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: shippingMethod
            inversedBy: null
            orphanRemoval: true
            orderBy: null
    lifecycleCallbacks: {  }
