_main:
    - Symfony\Bundle\FrameworkBundle\FrameworkBundle
    - Symfony\Bundle\SecurityBundle\SecurityBundle
    - Symfony\Bundle\TwigBundle\TwigBundle
    - Symfony\Bundle\MonologBundle\MonologBundle
    - Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle
    - Symfony\Bundle\AsseticBundle\AsseticBundle
    - Doctrine\Bundle\DoctrineBundle\DoctrineBundle
    - Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle
    - Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle
    - Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle
    - Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle
    - FOS\JsRoutingBundle\FOSJsRoutingBundle
    - Bazinga\Bundle\JsTranslationBundle\BazingaJsTranslationBundle
    - Liip\ImagineBundle\LiipImagineBundle
    - Ivory\LuceneSearchBundle\IvoryLuceneSearchBundle
    - Knp\DoctrineBehaviors\Bundle\DoctrineBehaviorsBundle
    - WellCommerce\Bundle\AdminBundle\WellCommerceAdminBundle
    - WellCommerce\Bundle\AppBundle\WellCommerceAppBundle
    - WellCommerce\Bundle\AttributeBundle\WellCommerceAttributeBundle
    - WellCommerce\Bundle\AvailabilityBundle\WellCommerceAvailabilityBundle
    - WellCommerce\Bundle\CartBundle\WellCommerceCartBundle
    - WellCommerce\Bundle\CategoryBundle\WellCommerceCategoryBundle
    - WellCommerce\Bundle\ContactBundle\WellCommerceContactBundle
    - WellCommerce\Bundle\ClientBundle\WellCommerceClientBundle
    - WellCommerce\Bundle\CoreBundle\WellCommerceCoreBundle
    - WellCommerce\Bundle\CountryBundle\WellCommerceCountryBundle
    - WellCommerce\Bundle\CouponBundle\WellCommerceCouponBundle
    - WellCommerce\Bundle\CurrencyBundle\WellCommerceCurrencyBundle
    - WellCommerce\Bundle\DelivererBundle\WellCommerceDelivererBundle
    - WellCommerce\Bundle\DictionaryBundle\WellCommerceDictionaryBundle
    - WellCommerce\Bundle\DistributionBundle\WellCommerceDistributionBundle
    - WellCommerce\Bundle\LocaleBundle\WellCommerceLocaleBundle
    - WellCommerce\Bundle\CompanyBundle\WellCommerceCompanyBundle
    - WellCommerce\Bundle\ShopBundle\WellCommerceShopBundle
    - WellCommerce\Bundle\LayeredNavigationBundle\WellCommerceLayeredNavigationBundle
    - WellCommerce\Bundle\LayoutBundle\WellCommerceLayoutBundle
    - WellCommerce\Bundle\MediaBundle\WellCommerceMediaBundle
    - WellCommerce\Bundle\NewsBundle\WellCommerceNewsBundle
    - WellCommerce\Bundle\ThemeBundle\WellCommerceThemeBundle
    - WellCommerce\Bundle\OrderBundle\WellCommerceOrderBundle
    - WellCommerce\Bundle\OAuthBundle\WellCommerceOAuthBundle
    - WellCommerce\Bundle\PageBundle\WellCommercePageBundle
    - WellCommerce\Bundle\PaymentBundle\WellCommercePaymentBundle
    - WellCommerce\Bundle\ProducerBundle\WellCommerceProducerBundle
    - WellCommerce\Bundle\ProductBundle\WellCommerceProductBundle
    - WellCommerce\Bundle\ProductStatusBundle\WellCommerceProductStatusBundle
    - WellCommerce\Bundle\ReportBundle\WellCommerceReportBundle
    - WellCommerce\Bundle\ReviewBundle\WellCommerceReviewBundle
    - WellCommerce\Bundle\RoutingBundle\WellCommerceRoutingBundle
    - WellCommerce\Bundle\SearchBundle\WellCommerceSearchBundle
    - WellCommerce\Bundle\ShippingBundle\WellCommerceShippingBundle
    - WellCommerce\Bundle\SmugglerBundle\WellCommerceSmugglerBundle
    - WellCommerce\Bundle\TaxBundle\WellCommerceTaxBundle
    - WellCommerce\Bundle\UnitBundle\WellCommerceUnitBundle
    - WellCommerce\Bundle\WishlistBundle\WellCommerceWishlistBundle

dev:
    - Symfony\Bundle\WebProfilerBundle\WebProfilerBundle
    - Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle

test:
    - Symfony\Bundle\WebProfilerBundle\WebProfilerBundle
    - Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle
