imports:
    - { resource: parameters.yml }
    - { resource: wellcommerce.yml }
#    - { resource: security.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }

framework:
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"
    fragments:       ~
    http_method_override: true
    profiler:
        matcher: { ip: "%developer_mode.ip%" }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          false
    use_controller: true
    filters:
        cssrewrite: ~
        less: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                #query_cache_driver:
                #    type: service
                #    id: doctrine.cache
                #metadata_cache_driver:
                #    type: service
                #    id: doctrine.cache
                #result_cache_driver:
                #    type: service
                #    id: doctrine.cache
                auto_mapping: true
                dql:
                    string_functions:
                        CONCAT_WS: DoctrineExtensions\Query\Mysql\ConcatWs
                        GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
                        IF_ELSE: DoctrineExtensions\Query\Mysql\IfElse
                        DAY: DoctrineExtensions\Query\Mysql\Day
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        QUARTER: DoctrineExtensions\Query\Mysql\Quarter
                        YEAR: DoctrineExtensions\Query\Mysql\Year
                        DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                        FIELD: DoctrineExtensions\Query\Mysql\Field
                filters:
                    locale:
                        class:   WellCommerce\Bundle\LocaleBundle\Doctrine\ORM\Filter\LocaleFilter
                        enabled: false

doctrine_migrations:
    dir_name:   %kernel.root_dir%/sql/migrations
    namespace:  WellCommerce\Migration
    table_name: migration
    name: WellCommerce Migrations

parameters:
    knp.doctrine_behaviors.blameable_listener.user_entity: WellCommerce\AdminBundle\Entity\User

fos_js_routing:
    router: router.default

#cmf_routing:
#    chain:
#        routers_by_id:
#            router.default:             100
#            cmf_routing.dynamic_router: 50
#    dynamic:
#        enabled: true
#        route_provider_service_id: router.provider.endpoint

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/media/images
    filter_sets:
        smallest:
            filters:
                thumbnail: { size: [60, 60], mode: outbound }
        small:
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
        normal:
            filters:
                thumbnail: { size: [175, 175], mode: outbound }
        medium:
            filters:
                thumbnail: { size: [240, 240], mode: outbound }
        large:
            filters:
                thumbnail: { size: [600, 600], mode: outbound }
        largest:
            filters:
                thumbnail: { size: [1200, 1200], mode: outbound }

services:
    doctrine.cache:
        class: %doctrine_cache.file_system.class%
        arguments: ["%kernel.root_dir%/cache/%kernel.environment%/doctrine"]

    client.failure.handler:
        class: WellCommerce\Bundle\AppBundle\Handler\LoginFailureHandler
        arguments:
          - @router
          - front.client.login
