imports:
    - { resource: config.yml }

framework:
    profiler: false

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %prod_log_path%
            level: debug
        console:
            type:  console
