imports:
    - { resource: parameters.yml }
    - { resource: wellcommerce.yml }
    - { resource: security.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }

framework:
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"
    fragments:       ~
    http_method_override: true
    assets: ~
    profiler:
        matcher: { ip: "%developer_mode.ip%" }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          false
    use_controller: true
    filters:
        cssrewrite: ~
        less: ~

parameters:
    knp.doctrine_behaviors.blameable_listener.user_entity: WellCommerce\AdminBundle\Entity\User
    knp.doctrine_behaviors.blameable_subscriber.user_callable.class: WellCommerce\Bundle\CoreBundle\Doctrine\ORM\Blameable\UserCallable

fos_js_routing:
    router: router.default

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/media/images
    filter_sets:
        smallest:
            filters:
                thumbnail: { size: [60, 60], mode: outbound }
        small:
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
        normal:
            filters:
                thumbnail: { size: [175, 175], mode: outbound }
        medium:
            filters:
                thumbnail: { size: [240, 240], mode: outbound }
        large:
            filters:
                thumbnail: { size: [600, 600], mode: outbound }
        largest:
            filters:
                thumbnail: { size: [1200, 1200], mode: outbound }

services:
    knp.doctrine_behaviors.blameable_subscriber.user_callable:
        class:           "%knp.doctrine_behaviors.blameable_subscriber.user_callable.class%"
        arguments:
            - "@security.token_storage"
        public:  false
    doctrine.cache:
        class: %doctrine_cache.file_system.class%
        arguments: ["%kernel.root_dir%/cache/%kernel.environment%/doctrine"]

    client.failure.handler:
        class: WellCommerce\Bundle\ClientBundle\Handler\LoginFailureHandler
        arguments:
          - "@router"
          - front.client.login
