fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

wellcommerce_locale:
    resource: "@WellCommerceLocaleBundle/Resources/config/routing.xml"
    prefix:   /admin/locale

wellcommerce_client:
    resource: "@WellCommerceClientBundle/Resources/config/routing.xml"
    prefix:   /admin/client

wellcommerce_company:
    resource: "@WellCommerceCompanyBundle/Resources/config/routing.xml"
    prefix:   /admin/company

wellcommerce_unit:
    resource: "@WellCommerceUnitBundle/Resources/config/routing.xml"
    prefix:   /admin/unit

wellcommerce_tax:
    resource: "@WellCommerceTaxBundle/Resources/config/routing.xml"
    prefix:   /admin/tax

