wellcommerce_company:
    resource: "@WellCommerceCompanyBundle/Resources/config/routing.xml"
    prefix:   /admin/company

wellcommerce_tax:
    resource: "@WellCommerceTaxBundle/Controller"
    type:     annotation

wellcommerce_core:
    resource: "@WellCommerceCoreBundle/Resources/config/routing.xml"
    prefix:   /

