wellcommerce_client:
    resource: "@WellCommerceClientBundle/Resources/config/routing.xml"
    prefix:   /admin/client

wellcommerce_company:
    resource: "@WellCommerceCompanyBundle/Resources/config/routing.xml"
    prefix:   /admin/company

