fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    options: { i18n: false }

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
    options: { i18n: false }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    options: { i18n: false }

wellcommerce_web:
    resource: "@WellCommerceWebBundle/Resources/config/routing.xml"
    prefix:   /

wellcommerce_user:
    resource: "@WellCommerceUserBundle/Resources/config/routing.xml"
    prefix:   /admin/user
    options: { i18n: false }

wellcommerce_intl:
    resource: "@WellCommerceIntlBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/
    options: { i18n: false }

wellcommerce_availability:
    resource: "@WellCommerceAvailabilityBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/availability
    options: { i18n: false }

wellcommerce_deliverer:
    resource: "@WellCommerceDelivererBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/deliverer
    options: { i18n: false }

wellcommerce_producer:
    resource: "@WellCommerceProducerBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/producer
    options: { i18n: false }

wellcommerce_product:
    resource: "@WellCommerceProductBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/product
    options: { i18n: false }

wellcommerce_category:
    resource: "@WellCommerceCategoryBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/category
    options: { i18n: false }

wellcommerce_client:
    resource: "@WellCommerceClientBundle/Resources/config/routing.xml"
    prefix:   /admin/crm/client
    options: { i18n: false }

wellcommerce_company:
    resource: "@WellCommerceCompanyBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/company
    options: { i18n: false }

wellcommerce_unit:
    resource: "@WellCommerceUnitBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/unit
    options: { i18n: false }

wellcommerce_tax:
    resource: "@WellCommerceTaxBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/tax
    options: { i18n: false }

wellcommerce_contact:
    resource: "@WellCommerceContactBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/contact
    options: { i18n: false }

wellcommerce_media:
    resource: "@WellCommerceMediaBundle/Resources/config/routing.xml"
    prefix:   /admin/media
    options: { i18n: false }

wellcommerce_layout:
    resource: "@WellCommerceLayoutBundle/Resources/config/routing.xml"
    prefix:   /admin/layout
    options: { i18n: false }

wellcommerce_theme:
    resource: "@WellCommerceThemeBundle/Resources/config/routing.xml"
    prefix:   /admin/theme
    options: { i18n: false }

wellcommerce_news:
    resource: "@WellCommerceNewsBundle/Resources/config/routing.xml"
    prefix:   /admin/news
    options: { i18n: false }

wellcommerce_payment:
    resource: "@WellCommercePaymentBundle/Resources/config/routing.xml"
    prefix:   /admin/payment
    options: { i18n: false }

wellcommerce_dashboard:
    resource: "@WellCommerceDashboardBundle/Resources/config/routing.xml"
    prefix:   /admin/dashboard
    options: { i18n: false }

wellcommerce_attribute:
    resource: "@WellCommerceAttributeBundle/Resources/config/routing.xml"
    prefix:   /admin/attribute
    options: { i18n: false }

root:
    path: /admin
    options: { i18n: false }
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: admin.user.index
        permanent: false

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: WellCommerceCoreBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]