fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

wellcommerce_user:
    resource: "@WellCommerceUserBundle/Resources/config/routing.xml"
    prefix:   /admin/user

wellcommerce_locale:
    resource: "@WellCommerceLocaleBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/locale

wellcommerce_currency:
    resource: "@WellCommerceCurrencyBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/currency

wellcommerce_availability:
    resource: "@WellCommerceAvailabilityBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/availability

wellcommerce_deliverer:
    resource: "@WellCommerceDelivererBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/deliverer

wellcommerce_producer:
    resource: "@WellCommerceProducerBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/producer

wellcommerce_product:
    resource: "@WellCommerceProductBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/product

wellcommerce_category:
    resource: "@WellCommerceCategoryBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/category

wellcommerce_client:
    resource: "@WellCommerceClientBundle/Resources/config/routing.xml"
    prefix:   /admin/crm/client

wellcommerce_company:
    resource: "@WellCommerceCompanyBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/company

wellcommerce_shop:
    resource: "@WellCommerceShopBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/shop

wellcommerce_unit:
    resource: "@WellCommerceUnitBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/unit

wellcommerce_tax:
    resource: "@WellCommerceTaxBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/tax

wellcommerce_contact:
    resource: "@WellCommerceContactBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/contact

wellcommerce_web:
    resource: "@WellCommerceWebBundle/Resources/config/routing.xml"
    prefix:   /

wellcommerce_media:
    resource: "@WellCommerceMediaBundle/Resources/config/routing.xml"
    prefix:   /admin/media

wellcommerce_layout:
    resource: "@WellCommerceLayoutBundle/Resources/config/routing.xml"
    prefix:   /admin/layout

wellcommerce_news:
    resource: "@WellCommerceNewsBundle/Resources/config/routing.xml"
    prefix:   /admin/news

wellcommerce_payment:
    resource: "@WellCommercePaymentBundle/Resources/config/routing.xml"
    prefix:   /admin/payment

wellcommerce_dashboard:
    resource: "@WellCommerceDashboardBundle/Resources/config/routing.xml"
    prefix:   /admin/dashboard

wellcommerce_attribute:
    resource: "@WellCommerceAttributeBundle/Resources/config/routing.xml"
    prefix:   /admin/attribute

root:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: admin.user.index
        permanent: false

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: WellCommerceCoreBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]