fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

wellcommerce_web:
    resource: "@WellCommerceWebBundle/Resources/config/routing.xml"
    prefix:   /

wellcommerce_admin:
    resource: "@WellCommerceAdminBundle/Resources/config/routing.xml"
    prefix:   /admin

wellcommerce_user:
    resource: "@WellCommerceUserBundle/Resources/config/routing.xml"
    prefix:   /admin/user

wellcommerce_routing:
    resource: "@WellCommerceRoutingBundle/Resources/config/routing.xml"
    prefix:   /admin/routing

wellcommerce_intl:
    resource: "@WellCommerceIntlBundle/Resources/config/routing.xml"

wellcommerce_availability:
    resource: "@WellCommerceAvailabilityBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/availability

wellcommerce_deliverer:
    resource: "@WellCommerceDelivererBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/deliverer

wellcommerce_producer:
    resource: "@WellCommerceProducerBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/producer

wellcommerce_product:
    resource: "@WellCommerceProductBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/product

wellcommerce_category:
    resource: "@WellCommerceCategoryBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/category

wellcommerce_client:
    resource: "@WellCommerceClientBundle/Resources/config/routing.xml"

wellcommerce_order:
    resource: "@WellCommerceOrderBundle/Resources/config/routing.xml"

wellcommerce_company:
    resource: "@WellCommerceMultiStoreBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/multi

wellcommerce_unit:
    resource: "@WellCommerceUnitBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/unit

wellcommerce_report:
    resource: "@WellCommerceReportBundle/Resources/config/routing.xml"
    prefix:   /admin/report

wellcommerce_tax:
    resource: "@WellCommerceTaxBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/tax

wellcommerce_media:
    resource: "@WellCommerceMediaBundle/Resources/config/routing.xml"
    prefix:   /admin/media

wellcommerce_layout:
    resource: "@WellCommerceLayoutBundle/Resources/config/routing.xml"
    prefix:   /admin/layout

wellcommerce_theme:
    resource: "@WellCommerceThemeBundle/Resources/config/routing.xml"
    prefix:   /admin/theme

wellcommerce_cms:
    resource: "@WellCommerceCmsBundle/Resources/config/routing.xml"
    prefix:   /admin/cms

wellcommerce_payment:
    resource: "@WellCommercePaymentBundle/Resources/config/routing.xml"

wellcommerce_shipping:
    resource: "@WellCommerceShippingBundle/Resources/config/routing.xml"
    prefix:   /admin/shipping

wellcommerce_attribute:
    resource: "@WellCommerceAttributeBundle/Resources/config/routing.xml"
    prefix:   /admin/attribute

wellcommerce_smuggler:
    resource: "@WellCommerceSmugglerBundle/Resources/config/routing.xml"
    prefix:   /admin/smuggler

wellcommerce_cart:
    resource: "@WellCommerceCartBundle/Resources/config/routing.xml"

root:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: admin.user.index
        permanent: false

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: WellCommerceRoutingBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]
