fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: WellCommerceCoreBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]

wellcommerce_user:
    resource: "@WellCommerceUserBundle/Resources/config/routing.xml"
    prefix:   /admin/user

wellcommerce_locale:
    resource: "@WellCommerceLocaleBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/locale

wellcommerce_currency:
    resource: "@WellCommerceCurrencyBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/currency

wellcommerce_availability:
    resource: "@WellCommerceAvailabilityBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/availability

wellcommerce_deliverer:
    resource: "@WellCommerceDelivererBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/deliverer

wellcommerce_producer:
    resource: "@WellCommerceProducerBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/producer

wellcommerce_category:
    resource: "@WellCommerceCategoryBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/category

wellcommerce_client:
    resource: "@WellCommerceClientBundle/Resources/config/routing.xml"
    prefix:   /admin/crm/client

wellcommerce_company:
    resource: "@WellCommerceCompanyBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/company

wellcommerce_shop:
    resource: "@WellCommerceShopBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/shop

wellcommerce_unit:
    resource: "@WellCommerceUnitBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/unit

wellcommerce_tax:
    resource: "@WellCommerceTaxBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/tax

wellcommerce_contact:
    resource: "@WellCommerceContactBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/contact

wellcommerce_web:
    resource: "@WellCommerceWebBundle/Resources/config/routing.xml"
    prefix:   /

wellcommerce_media:
    resource: "@WellCommerceMediaBundle/Resources/config/routing.xml"
    prefix:   /admin/media

root:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: admin.user.index
        permanent: true

