fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

wellcommerce_locale:
    resource: "@WellCommerceLocaleBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/locale

wellcommerce_category:
    resource: "@WellCommerceCategoryBundle/Resources/config/routing.xml"
    prefix:   /admin/catalog/category

wellcommerce_client:
    resource: "@WellCommerceClientBundle/Resources/config/routing.xml"
    prefix:   /admin/crm/client

wellcommerce_company:
    resource: "@WellCommerceCompanyBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/company

wellcommerce_shop:
    resource: "@WellCommerceShopBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/shop

wellcommerce_unit:
    resource: "@WellCommerceUnitBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/unit

wellcommerce_tax:
    resource: "@WellCommerceTaxBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/tax

wellcommerce_contact:
    resource: "@WellCommerceContactBundle/Resources/config/routing.xml"
    prefix:   /admin/configuration/contact

