security:
    session_fixation_strategy:  none
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern:   ^/admin
            anonymous: ~
            provider: administrators
            form_login:
                login_path: admin.user.login
                check_path: admin.user.login_check
                default_target_path: admin.user.index
            logout:
                path:   admin.user.logout
                target: admin.user.login
        client:
            pattern:   ^/
            anonymous: ~
            provider: clients
            form_login:
                login_path: front.client.login
                check_path: front.client.login_check
                default_target_path: front.client_order.index
                failure_handler: client.failure.handler
            logout:
                path:   front.client.logout
                target: front.client.login

    access_control:
        - { path: ^/admin/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin$, roles: ROLE_ADMIN }
        - { path: ^/client/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client, roles: ROLE_CLIENT }
        - { path: ^/client$, roles: ROLE_CLIENT }

    providers:
        administrators:
            entity: { class: WellCommerceAppBundle:User }
        clients:
            entity: { class: WellCommerceAppBundle:Client }

    encoders:
        WellCommerce\Bundle\AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
        WellCommerce\Bundle\AppBundle\Entity\Client:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
