security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern:   ^/admin
            anonymous: ~
            form_login:
                login_path: admin.user.login
                check_path: admin.user.login_check
                default_target_path: admin.user.index
            logout:
                path:   admin.user.logout
                target: admin.user.login

    access_control:
        - { path: ^/admin/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin$, roles: ROLE_ADMIN }

    providers:
        administrators:
            entity: { class: WellCommerceUserBundle:User }

    encoders:
        WellCommerce\Bundle\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
