imports:
    - { resource: "@WellCommerceAppBundle/Resources/config/wellcommerce.yml" }

parameters:
    fixtures_load_order:
        WellCommerce\Bundle\AdminBundle\DataFixtures\ORM\LoadAdminMenuData: 0
        WellCommerce\Bundle\ThemeBundle\DataFixtures\ORM\LoadThemeData: 10
        WellCommerce\Bundle\CompanyBundle\DataFixtures\ORM\LoadCompanyData: 20
        WellCommerce\Bundle\CurrencyBundle\DataFixtures\ORM\LoadCurrencyData: 30
        WellCommerce\Bundle\LocaleBundle\DataFixtures\ORM\LoadLocaleData: 40
        WellCommerce\Bundle\OrderBundle\DataFixtures\ORM\LoadOrderStatusGroupData: 41
        WellCommerce\Bundle\OrderBundle\DataFixtures\ORM\LoadOrderStatusData: 42
        WellCommerce\Bundle\ShopBundle\DataFixtures\ORM\LoadShopData: 50
        WellCommerce\Bundle\AdminBundle\DataFixtures\ORM\LoadUserData: 60
        WellCommerce\Bundle\TaxBundle\DataFixtures\ORM\LoadTaxData: 70
        WellCommerce\Bundle\ClientBundle\DataFixtures\ORM\LoadClientGroupData: 80
        WellCommerce\Bundle\ClientBundle\DataFixtures\ORM\LoadClientData: 90
        WellCommerce\Bundle\UnitBundle\DataFixtures\ORM\LoadUnitData: 110
        WellCommerce\Bundle\ContactBundle\DataFixtures\ORM\LoadContactData: 130
        WellCommerce\Bundle\MediaBundle\DataFixtures\ORM\LoadMediaData: 135
        WellCommerce\Bundle\DelivererBundle\DataFixtures\ORM\LoadDelivererData: 140
        WellCommerce\Bundle\AvailabilityBundle\DataFixtures\ORM\LoadAvailabilityData: 150
        WellCommerce\Bundle\ProducerBundle\DataFixtures\ORM\LoadProducerData: 160
        WellCommerce\Bundle\AttributeBundle\DataFixtures\ORM\LoadAttributeData: 170
        WellCommerce\Bundle\CategoryBundle\DataFixtures\ORM\LoadCategoryData: 180
        WellCommerce\Bundle\ProductStatusBundle\DataFixtures\ORM\LoadProductStatusData: 190
        WellCommerce\Bundle\ProductBundle\DataFixtures\ORM\LoadProductData: 200
        WellCommerce\Bundle\LayoutBundle\DataFixtures\ORM\LoadLayoutBoxData: 210
        WellCommerce\Bundle\ShippingBundle\DataFixtures\ORM\LoadShippingMethodData: 220
        WellCommerce\Bundle\PaymentBundle\DataFixtures\ORM\LoadPaymentMethodData: 230
        WellCommerce\Bundle\PageBundle\DataFixtures\ORM\LoadPageData: 240
    fixtures_product_limit: 100
    enabled_fixtures:
        WellCommerce\Bundle\AdminBundle\DataFixtures\ORM\LoadAdminMenuData: true
        WellCommerce\Bundle\ThemeBundle\DataFixtures\ORM\LoadThemeData: true
        WellCommerce\Bundle\CompanyBundle\DataFixtures\ORM\LoadCompanyData: true
        WellCommerce\Bundle\CurrencyBundle\DataFixtures\ORM\LoadCurrencyData: true
        WellCommerce\Bundle\LocaleBundle\DataFixtures\ORM\LoadLocaleData: true
        WellCommerce\Bundle\OrderBundle\DataFixtures\ORM\LoadOrderStatusGroupData: true
        WellCommerce\Bundle\OrderBundle\DataFixtures\ORM\LoadOrderStatusData: true
        WellCommerce\Bundle\ShopBundle\DataFixtures\ORM\LoadShopData: true
        WellCommerce\Bundle\AdminBundle\DataFixtures\ORM\LoadUserData: true
        WellCommerce\Bundle\TaxBundle\DataFixtures\ORM\LoadTaxData: true
        WellCommerce\Bundle\ClientBundle\DataFixtures\ORM\LoadClientGroupData: true
        WellCommerce\Bundle\ClientBundle\DataFixtures\ORM\LoadClientData: true
        WellCommerce\Bundle\UnitBundle\DataFixtures\ORM\LoadUnitData: true
        WellCommerce\Bundle\ContactBundle\DataFixtures\ORM\LoadContactData: true
        WellCommerce\Bundle\MediaBundle\DataFixtures\ORM\LoadMediaData: true
        WellCommerce\Bundle\DelivererBundle\DataFixtures\ORM\LoadDelivererData: true
        WellCommerce\Bundle\AvailabilityBundle\DataFixtures\ORM\LoadAvailabilityData: true
        WellCommerce\Bundle\ProducerBundle\DataFixtures\ORM\LoadProducerData: true
        WellCommerce\Bundle\AttributeBundle\DataFixtures\ORM\LoadAttributeData: true
        WellCommerce\Bundle\CategoryBundle\DataFixtures\ORM\LoadCategoryData: true
        WellCommerce\Bundle\ProductStatusBundle\DataFixtures\ORM\LoadProductStatusData: true
        WellCommerce\Bundle\ProductBundle\DataFixtures\ORM\LoadProductData: true
        WellCommerce\Bundle\LayoutBundle\DataFixtures\ORM\LoadLayoutBoxData: true
        WellCommerce\Bundle\ShippingBundle\DataFixtures\ORM\LoadShippingMethodData: true
        WellCommerce\Bundle\PaymentBundle\DataFixtures\ORM\LoadPaymentMethodData: true
        WellCommerce\Bundle\PageBundle\DataFixtures\ORM\LoadPageData: true
