parameters:
    fixtures_load_order:
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadAdminMenuData: 0
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadThemeData: 10
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadCompanyData: 20
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadCurrencyData: 30
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadLocaleData: 40
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadOrderStatusGroupData: 41
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadOrderStatusData: 42
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadShopData: 50
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadUserData: 60
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadTaxData: 70
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadClientGroupData: 80
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadClientData: 90
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadUnitData: 110
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadContactData: 130
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadMediaData: 135
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadDelivererData: 140
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadAvailabilityData: 150
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadProducerData: 160
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadAttributeData: 170
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadCategoryData: 180
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadProductStatusData: 190
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadProductData: 200
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadLayoutBoxData: 210
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadShippingMethodData: 220
        WellCommerce\Bundle\AppBundle\DataFixtures\ORM\LoadPaymentMethodData: 230
    fixtures_product_limit: 100

well_commerce_core:
    type: %search_engine%
    search_term_min_length: 3
    media_upload_dir: %kernel.root_dir%


