WellCommerce\Bundle\CoreBundle\Entity\ContactDetails:
    type: embeddable
    fields:
        phone:
            type: string
            length: 255
            nullable: true
        secondaryPhone:
            type: string
            length: 255
            nullable: true
            column: secondary_phone
        email:
            type: string
            length: 255
            nullable: true
