WellCommerce\Bundle\AppBundle\Entity\Attribute\GroupTranslation:
    type: entity
    table: attribute_group_translation
    fields:
        name:
            type: string
            length: 255
            nullable: false
