# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\AppBundle\Entity\MailerConfiguration:
    type: embeddable
    fields:
        from:
            type: string
            length: 64
            nullable: true
        host:
            type: string
            length: 64
            nullable: true
        port:
            type: integer
            nullable: true
        user:
            type: string
            length: 64
            nullable: true
        pass:
            type: string
            length: 64
            nullable: true
