WellCommerce\Bundle\AppBundle\Entity\PageRoute:
    type: entity
    table: route_page
    manyToOne:
        identifier:
            targetEntity: WellCommerce\Bundle\AppBundle\Entity\Page
            fetch: LAZY
            joinColumns:
                foreign_id:
                    referencedColumnName: id
                    onDelete: CASCADE
