WellCommerce\Bundle\AppBundle\Entity\ThemeCss:
    type: entity
    table: theme_css
    repositoryClass: WellCommerce\Bundle\AppBundle\Repository\ThemeCssRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        class:
            type: string
            length: 255
            nullable: false
        selector:
            type: string
            length: 255
            nullable: false
        attribute:
            type: string
            length: 255
            nullable: false
    manyToOne:
        theme:
            targetEntity: WellCommerce\Bundle\AppBundle\Entity\Theme
            fetch: LAZY
            inversedBy: css
            joinColumns:
                theme_id:
                    referencedColumnName: id
