WellCommerce\Bundle\AppBundle\Entity\UserGroup:
    type: entity
    table: user_group
    repositoryClass: WellCommerce\Bundle\AppBundle\Repository\UserGroupRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: 30
            unique: false
            nullable: false
            precision: 0
    manyToMany:
        users:
            targetEntity: WellCommerce\Bundle\AppBundle\Entity\User
            fetch: LAZY
            mappedBy: groups
    oneToMany:
        permissions:
            targetEntity: WellCommerce\Bundle\AppBundle\Entity\UserGroupPermission
            cascade:
                - all
            fetch: LAZY
            mappedBy: group
            orphanRemoval: true
