# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\AppBundle\Entity\MailerConfiguration:
    fields:
        from:
            groups:
                - default
                - mailer_configuration
        host:
            groups:
                - default
                - mailer_configuration
        port:
            groups:
                - default
                - mailer_configuration
        user:
            groups:
                - default
                - mailer_configuration
        pass:
            groups:
                - default
                - mailer_configuration
    associations: {  }
    callbacks: {  }
