# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

_admin_availability:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/availability/admin.yml"
    prefix: /admin/catalog/availability

_admin_category:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/category/admin.yml"
    prefix: /admin/catalog/category

_admin_deliverer:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/deliverer/admin.yml"
    prefix: /admin/catalog/deliverer

_admin_producer:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/producer/admin.yml"
    prefix: /admin/catalog/producer

_admin_unit:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing/unit/admin.yml"
    prefix: /admin/catalog/unit
