WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethod:
    type: entity
    table: payment_method
    repositoryClass: WellCommerce\Bundle\PaymentBundle\Repository\PaymentMethodRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        processor:
            type: string
            length: 64
            nullable: false
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
        hierarchy:
            type: integer
            nullable: false
            options:
                default: 0
