WellCommerce\Bundle\CmsBundle\Entity\News:
    type: entity
    table: news
    repositoryClass: WellCommerce\Bundle\CmsBundle\Repository\NewsRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        publish:
            type: boolean
            nullable: false
            options:
                default: true
        startDate:
            type: datetime
            nullable: true
        endDate:
            type: datetime
            nullable: true
        featured:
            type: boolean
            nullable: false
            options:
                default: false
    manyToOne:
        photo:
            targetEntity: WellCommerce\Bundle\CmsBundle\Entity\Media
            fetch: LAZY
            joinColumns:
                photo_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
