WellCommerce\AppBundle\Entity\ClientGroupTranslation:
    type: entity
    table: client_group_translation
    id: {  }
    fields:
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
