WellCommerce\AppBundle\Entity\OrderStatusGroup:
    type: entity
    table: order_status_group
    repositoryClass: WellCommerce\AppBundle\Repository\OrderStatusGroupRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
