WellCommerce\AppBundle\Entity\PaymentMethodConfiguration:
    type: entity
    table: payment_method_configuration
    repositoryClass: WellCommerce\AppBundle\Repository\PaymentMethodConfigurationRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
        value:
            type: string
            nullable: false
    manyToOne:
        paymentMethod:
            targetEntity: WellCommerce\AppBundle\Entity\PaymentMethod
            fetch: LAZY
            inversedBy: configuration
            joinColumns:
                payment_method_id:
                    referencedColumnName: id
                    onDelete: CASCADE
