WellCommerce\AppBundle\Entity\Unit:
    type: entity
    table: unit
    repositoryClass: WellCommerce\AppBundle\Repository\UnitRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
