well_commerce_shop:
    configuration:
        shop:
            orm:
                factory: WellCommerce\Bundle\ShopBundle\Factory\ShopFactory
                repository: WellCommerce\Bundle\ShopBundle\Repository\ShopRepository
                mapping: "@WellCommerceShopBundle/Resources/config/doctrine/Shop.orm.yml"
                entity: WellCommerce\Bundle\ShopBundle\Entity\Shop
            api:
                exposed: true
                dataset: shop.dataset.admin
                manager: shop.manager

doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\ShopBundle\Entity\ShopInterface: WellCommerce\Bundle\ShopBundle\Entity\Shop
