services:
    datagrid.configurator:
        class: WellCommerce\Component\DataGrid\Configurator\DataGridConfigurator
        arguments: ['@event_dispatcher']

    twig.extension.datagrid:
        class: WellCommerce\Bundle\AppBundle\Twig\DataGridExtension
        arguments: ['WellCommerceCoreBundle:DataGrid:datagrid.html.twig', '@twig']
        tags:
            - { name: twig.extension }
