WellCommerce\Bundle\ProducerBundle\Entity\ProducerTranslation:
    type: entity
    table: producer_translation
    embedded:
        meta:
            class: WellCommerce\Bundle\CoreBundle\Entity\Meta
    fields:
        name:
            type: string
            length: 255
            nullable: false
        shortDescription:
            type: text
            column: short_description
        description:
            type: text
        slug:
            type: string
            length: 255
            unique: true
            nullable: false
    oneToOne:
        route:
            targetEntity: WellCommerce\Bundle\ProducerBundle\Entity\ProducerRoute
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                route_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
