# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\ShopBundle\Entity\ShopInterface: WellCommerce\Bundle\ShopBundle\Entity\Shop

well_commerce_doctrine:
    configuration:
        shop:
            factory: WellCommerce\Bundle\ShopBundle\Factory\ShopFactory
            repository: WellCommerce\Bundle\ShopBundle\Repository\ShopRepository
            mapping: "@WellCommerceShopBundle/Resources/config/doctrine/Shop.orm.yml"
            entity: WellCommerce\Bundle\ShopBundle\Entity\Shop
