# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.user.index:
    path: /admin/user/index
    defaults:
        _controller: 'user.controller.admin:indexAction'
    options:
        require_admin_permission: user.index

admin.user.grid:
    path: /admin/user/grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'user.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: user.index

admin.user.add:
    path: /admin/user/add
    defaults:
        _controller: 'user.controller.admin:addAction'
    options:
        require_admin_permission: user.add

admin.user.edit:
    path: '/admin/user/edit/{id}'
    defaults:
        _controller: 'user.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: user.edit

admin.user.delete:
    path: '/admin/user/delete/{id}'
    defaults:
        _controller: 'user.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: user.delete

admin.user.delete_group:
    path: '/admin/user/delete_group'
    defaults:
        _controller: 'user.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: user.delete

admin.user.login:
    path: /admin/user/login
    defaults:
        _controller: 'user.controller.admin:loginAction'

admin.user.reset_password:
    path: /admin/user/reset
    defaults:
        _controller: 'user.controller.admin:resetPasswordAction'

admin.user.login_check:
    path: /admin/user/login_check

admin.user.logout:
    path: /admin/user/logout
