parameters:
    search_term_min_length: 3

well_commerce_search:
    indexes:
        product:
            indexer: lucene.indexer.product
            provider: lucene.provider.product
        producer:
            indexer: lucene.indexer.producer
            provider: lucene.provider.producer

