parameters:
    search_term_min_length: 3

well_commerce_search:
    engine:
        adapters:
            elasticsearch:
                class: WellCommerce\Bundle\SearchBundle\Adapter\ElasticSearchAdapter
                options:
                    number_of_shards: 2
                    number_of_replicas: 0
            lucene:
                class: WellCommerce\Bundle\SearchBundle\Adapter\ZendLuceneAdapter
                options:
                    index_file: "%kernel.root_dir%/lucene/"
                    max_buffered_docs: 10
                    max_merge_docs: 100000
                    merge_factor: 10
        indexes:
            product:
                adapter: "%search_adapter%"
                repository: product.repository
                fields:
                    sku:
                        indexed: true
                        type: text
                        boost: 1
                        translatable: false
                        property: sku
                        analyzer: ~
                    name:
                        indexed: true
                        type: text
                        boost: 1
                        translatable: true
                        property: name
                        analyzer: ~
                    short_description:
                        indexed: true
                        type: text
                        boost: 0.5
                        translatable: true
                        property: shortDescription
                        analyzer: ~
                    author:
                        indexed: true
                        type: text
                        boost: 1
                        translatable: false
                        property: author
                        analyzer: ~
                    isbn:
                        indexed: true
                        type: text
                        boost: 1
                        translatable: false
                        property: isbn
                        analyzer: ~
