
services:
    oauth.controller.facebook:
        class: WellCommerce\Bundle\OAuthBundle\Controller\FacebookController
        arguments: ['@facebook.client.manager']
        calls:
            - [setContainer, ['@service_container']]

    oauth.authentificator.facebook:
        class: WellCommerce\Bundle\OAuthBundle\Security\FacebookAuthenticator
        arguments: ["@facebook.client.manager", "@router.helper", "%facebook%"]

    facebook.client.manager:
        class: WellCommerce\Bundle\OAuthBundle\Manager\FacebookClientManager
        arguments: ["@client.factory","@client.repository"]
        calls:
            - [setContainer, ['@service_container']]