
services:
    oauth.controller.facebook:
        class: WellCommerce\Bundle\OAuthBundle\Controller\FacebookController
        arguments: ['@client.manager']
        calls:
            - [setContainer, ['@service_container']]

    oauth.authentificator.facebook:
        class: WellCommerce\Bundle\OAuthBundle\Security\FacebookAuthenticator
        arguments: ["@client.manager", "@router.helper", "%facebook%"]
