wellcommerce_web:
    resource: "@WellCommerceWebBundle/Resources/config/routing.xml"

wellcommerce_admin:
    resource: "@WellCommerceAdminBundle/Resources/config/routing.xml"

wellcommerce_routing:
    resource: "@WellCommerceRoutingBundle/Resources/config/routing.xml"

wellcommerce_intl:
    resource: "@WellCommerceIntlBundle/Resources/config/routing.xml"

wellcommerce_catalog:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing.xml"

wellcommerce_client:
    resource: "@WellCommerceClientBundle/Resources/config/routing.xml"

wellcommerce_order:
    resource: "@WellCommerceOrderBundle/Resources/config/routing.xml"

wellcommerce_coupon:
    resource: "@WellCommerceCouponBundle/Resources/config/routing.xml"

wellcommerce_company:
    resource: "@WellCommerceMultiStoreBundle/Resources/config/routing.xml"

wellcommerce_unit:
    resource: "@WellCommerceCatalogBundle/Resources/config/routing.xml"

wellcommerce_report:
    resource: "@WellCommerceReportBundle/Resources/config/routing.xml"

wellcommerce_tax:
    resource: "@WellCommerceTaxBundle/Resources/config/routing.xml"

wellcommerce_media:
    resource: "@WellCommerceMediaBundle/Resources/config/routing.xml"

wellcommerce_layout:
    resource: "@WellCommerceLayoutBundle/Resources/config/routing.xml"

wellcommerce_cms:
    resource: "@WellCommerceCmsBundle/Resources/config/routing.xml"

wellcommerce_payment:
    resource: "@WellCommercePaymentBundle/Resources/config/routing.xml"

wellcommerce_shipping:
    resource: "@WellCommerceShippingBundle/Resources/config/routing.xml"

wellcommerce_smuggler:
    resource: "@WellCommerceSmugglerBundle/Resources/config/routing.xml"

wellcommerce_cart:
    resource: "@WellCommerceCartBundle/Resources/config/routing.xml"
