well_commerce_category:
    services:
        category:
            auto_services:
                factory: WellCommerce\Bundle\CategoryBundle\Factory\CategoryFactory
                repository: WellCommerce\Bundle\CategoryBundle\Repository\CategoryRepository
            orm_configuration:
                mapping: "@WellCommerceCategoryBundle/Resources/config/doctrine/Category.orm.yml"
                entity: WellCommerce\Bundle\CategoryBundle\Entity\Category
        category_route:
            auto_services:
                factory: ~
                repository: ~
            orm_configuration:
                mapping: "@WellCommerceCategoryBundle/Resources/config/doctrine/CategoryRoute.orm.yml"
                entity: WellCommerce\Bundle\CategoryBundle\Entity\CategoryRoute
        category_translation:
            auto_services:
                factory: ~
                repository: ~
            orm_configuration:
                mapping: "@WellCommerceCategoryBundle/Resources/config/doctrine/CategoryTranslation.orm.yml"
                entity: WellCommerce\Bundle\CategoryBundle\Entity\CategoryTranslation
