# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    search.layout_box.configurator:
        class: WellCommerce\Bundle\SearchBundle\Configurator\SearchBoxConfigurator
        tags:
            - { name: layout_box.configurator }
        arguments: [Search, search.layout_box.controller, '@translator.helper']
        calls:
            - [setContainer, ['@service_container']]
