WellCommerce\AdminBundle\Entity\UserGroupPermission:
    type: entity
    table: user_group_permission
    repositoryClass: WellCommerce\AdminBundle\Repository\UserGroupPermissionRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 64
            column: name
        enabled:
            type: boolean
    manyToOne:
        group:
            targetEntity: WellCommerce\AdminBundle\Entity\UserGroup
            fetch: LAZY
            inversedBy: permissions
            joinColumns:
                user_group_id:
                    referencedColumnName: id
            orphanRemoval: true
