WellCommerce\CatalogBundle\Entity\ProductRoute:
    type: entity
    table: route_product
    manyToOne:
        identifier:
            targetEntity: WellCommerce\CatalogBundle\Entity\Product
            fetch: LAZY
            joinColumns:
                foreign_id:
                    referencedColumnName: id
                    onDelete: CASCADE
