WellCommerce\Bundle\CatalogBundle\Entity\CategoryRoute:
    type: entity
    table: route_category
    manyToOne:
        identifier:
            targetEntity: WellCommerce\Bundle\CatalogBundle\Entity\Category
            fetch: LAZY
            joinColumns:
                foreign_id:
                    referencedColumnName: id
                    onDelete: CASCADE
