WellCommerce\Bundle\CatalogBundle\Entity\ProductStatusRoute:
    type: entity
    table: route_product_status
    manyToOne:
        identifier:
            targetEntity: WellCommerce\Bundle\CatalogBundle\Entity\ProductStatus
            fetch: LAZY
            joinColumns:
                foreign_id:
                    referencedColumnName: id
                    onDelete: CASCADE
