WellCommerce\Bundle\AvailabilityBundle\Entity\AvailabilityTranslation:
    type: entity
    table: availability_translation
    fields:
        name:
            type: string
            length: 255
            nullable: false
        type:
            type: string
            length: 255
            nullable: false
        type222:
            type: string
            length: 255
            nullable: false
