imports:
    - { resource: parameters.yml }

wellcommerce_profiler:
     enabled:  "%profiler%"

wellcommerce_core:
    database:
        driver:     "%database_driver%"
        host:       "%database_host%"
        database:   "%database_name%"
        username:   "%database_user%"
        password:   "%database_pass%"
        port:       "%database_port%"
        charset:    utf8
        collation:  utf8_unicode_ci
        prefix:     "%database_prefix%"

    router:
        cache_dir:              "%application.root_path%var"
        generator_cache_class:  WellCommerceUrlGenerator
        matcher_cache_class:    WellCommerceUrlMatcher

    session:
        db_table:  "%session_db_table%"