# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    shop.controller.admin:
        class: WellCommerce\Bundle\ShopBundle\Controller\Admin\ShopController
        arguments: ['@shop.manager', '@shop.form_builder.admin', '@shop.datagrid']
        calls:
            - [setContainer, ['@service_container']]

    shop.form_builder.admin:
        class: WellCommerce\Bundle\ShopBundle\Form\Admin\ShopFormBuilder
        tags:
            - { name: form_builder }
