WellCommerce\Bundle\RoutingBundle\Entity\Route:
    type: entity
    table: route
    inheritanceType: JOINED
    discriminatorColumn:
        name: type
        type: string
        fieldName: type
    discriminatorMap:
        route: WellCommerce\Bundle\RoutingBundle\Entity\Route
        product: WellCommerce\Bundle\ProductBundle\Entity\ProductRoute
        product_status: WellCommerce\Bundle\ProductStatusBundle\Entity\ProductStatusRoute
        producer: WellCommerce\Bundle\ProducerBundle\Entity\ProducerRoute
        category: WellCommerce\Bundle\CategoryBundle\Entity\CategoryRoute
        page: WellCommerce\Bundle\PageBundle\Entity\PageRoute
    repositoryClass: WellCommerce\Bundle\RoutingBundle\Repository\RouteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        path:
            type: string
            unique: false
            nullable: false
        locale:
            type: string
            length: 255
            unique: false
            nullable: false
