WellCommerce\Bundle\ProductStatusBundle\Entity\ProductStatusRoute:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: route_product_status
    manyToOne:
        identifier:
            targetEntity: WellCommerce\Bundle\ProductStatusBundle\Entity\ProductStatus
            fetch: LAZY
            joinColumns:
                foreign_id:
                    referencedColumnName: id
                    onDelete: CASCADE
