WellCommerce\Bundle\DelivererBundle\Entity\DelivererTranslation:
    type: entity
    table: deliverer_translation
    id: {  }
    fields:
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
