WellCommerce\Bundle\ProductBundle\Entity\ProductStatus:
    type: entity
    table: product_status
    repositoryClass: WellCommerce\Bundle\ProductBundle\Repository\ProductStatusRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    manyToMany:
        products:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\Product
            cascade: {  }
            fetch: LAZY
            mappedBy: statuses
            inversedBy: null
            joinTable: {  }
            orderBy: null
    lifecycleCallbacks: {  }
