WellCommerce\Bundle\ProductBundle\Entity\ProductStatusTranslation:
    type: entity
    table: product_status_translation
    id: {  }
    fields:
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        cssClass:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            column: css_class
        metaTitle:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
            column: meta_title
        metaKeywords:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: meta_keywords
        metaDescription:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: meta_description
        slug:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
    oneToOne:
        route:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\ProductStatusRoute
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                route_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
