WellCommerce\CommonBundle\Entity\Company:
    type: entity
    table: company
    repositoryClass: WellCommerce\CommonBundle\Repository\CompanyRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    embedded:
        address:
            class: WellCommerce\CommonBundle\Entity\CompanyAddress
            columnPrefix: address_
    fields:
        name:
            type: string
            length: 255
            nullable: false
        shortName:
            type: string
            length: 255
            nullable: false
            column: short_name
    manyToOne:
        photo:
            targetEntity: WellCommerce\CmsBundle\Entity\Media
            fetch: LAZY
            joinColumns:
                photo_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
