WellCommerce\CommonBundle\Entity\Tax:
    type: entity
    table: tax
    repositoryClass: WellCommerce\CommonBundle\Repository\TaxRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        value:
            type: decimal
            scale: 2
            precision: 15
            nullable: false
