WellCommerce\Bundle\PageBundle\Entity\PageRoute:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: route_page
    manyToOne:
        identifier:
            targetEntity: WellCommerce\Bundle\PageBundle\Entity\Page
            fetch: LAZY
            joinColumns:
                foreign_id:
                    referencedColumnName: id
                    onDelete: CASCADE
