WellCommerce\Bundle\NewsBundle\Entity\NewsRoute:
    type: entity
    table: route_news
    manyToOne:
        identifier:
            targetEntity: WellCommerce\Bundle\NewsBundle\Entity\News
            fetch: LAZY
            joinColumns:
                foreign_id:
                    referencedColumnName: id
                    onDelete: CASCADE
