well_commerce_contact:
    services:
        contact:
            auto_services:
                factory: WellCommerce\Bundle\ContactBundle\Factory\ContactFactory
                repository: WellCommerce\Bundle\ContactBundle\Repository\ContactRepository
            orm_configuration:
                mapping: "@WellCommerceContactBundle/Resources/config/doctrine/Contact.orm.yml"
                entity: WellCommerce\Bundle\ContactBundle\Entity\Contact
        contact_translation:
            orm_configuration:
                mapping: "@WellCommerceContactBundle/Resources/config/doctrine/ContactTranslation.orm.yml"
                entity: WellCommerce\Bundle\ContactBundle\Entity\ContactTranslation
