WellCommerce\Bundle\MultiStoreBundle\Entity\Company:
    type: entity
    table: Company
    repositoryClass: WellCommerce\Bundle\MultiStoreBundle\Repository\CompanyRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: false
        shortName:
            type: string
            length: 255
            nullable: false
            column: short_name
        street:
            type: string
            length: 255
            nullable: true
        streetNo:
            type: string
            length: 255
            nullable: true
            column: street_no
        flatNo:
            type: string
            length: 255
            nullable: true
            column: flat_no
        postCode:
            type: string
            length: 255
            nullable: true
            column: post_code
        province:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
        country:
            type: string
            length: 3
            nullable: true
    manyToOne:
        photo:
            targetEntity: WellCommerce\Bundle\MediaBundle\Entity\Media
            fetch: LAZY
            joinColumns:
                photo_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
