WellCommerce\Bundle\MultiStoreBundle\Entity\Shop:
    type: entity
    table: Shop
    repositoryClass: WellCommerce\Bundle\MultiStoreBundle\Repository\ShopRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        url:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        defaultCountry:
            type: string
            scale: 0
            length: 3
            unique: false
            nullable: true
            precision: 0
            column: default_country
    manyToOne:
        company:
            targetEntity: WellCommerce\Bundle\MultiStoreBundle\Entity\Company
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                company_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
            orphanRemoval: false
        theme:
            targetEntity: WellCommerce\Bundle\ThemeBundle\Entity\Theme
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                theme_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
            orphanRemoval: false
        defaultOrderStatus:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\OrderStatus
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                default_order_status_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
            orphanRemoval: false
    manyToMany:
        products:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\Product
            cascade: {  }
            fetch: LAZY
            mappedBy: shops
            inversedBy: null
            joinTable: {  }
            orderBy: null
        categories:
            targetEntity: WellCommerce\Bundle\CategoryBundle\Entity\Category
            cascade: {  }
            fetch: LAZY
            mappedBy: shops
            inversedBy: null
            joinTable: {  }
            orderBy: null
        producers:
            targetEntity: WellCommerce\Bundle\ProducerBundle\Entity\Producer
            cascade: {  }
            fetch: LAZY
            mappedBy: shops
            inversedBy: null
            joinTable: {  }
            orderBy: null
        pages:
            targetEntity: WellCommerce\Bundle\CmsBundle\Entity\Page
            cascade: {  }
            fetch: LAZY
            mappedBy: shops
            inversedBy: null
            joinTable: {  }
            orderBy: null
    lifecycleCallbacks: {  }
