WellCommerce\Bundle\OrderBundle\Entity\OrderStatusGroupTranslation:
    type: entity
    table: order_status_group_translation
    id: {  }
    fields:
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
