WellCommerce\Bundle\OrderBundle\Entity\OrderModifier:
    type: entity
    table: orders_modifier
    repositoryClass: WellCommerce\Bundle\OrderBundle\Repository\OrderModifierRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        netValue:
            type: decimal
            scale: 4
            length: null
            unique: false
            nullable: false
            precision: 15
            column: net_value
        taxValue:
            type: decimal
            scale: 4
            length: null
            unique: false
            nullable: false
            precision: 15
            column: tax_value
        grossValue:
            type: decimal
            scale: 4
            length: null
            unique: false
            nullable: false
            precision: 15
            column: gross_value
        increase:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: is_increase
        hierarchy:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            options:
                default: 0
        modifierDetails.name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            originalClass: WellCommerce\Bundle\OrderBundle\Entity\OrderModifierDetails
            declaredField: modifierDetails
            originalField: name
            column: modifier_detalils_name
        modifierDetails.description:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            originalClass: WellCommerce\Bundle\OrderBundle\Entity\OrderModifierDetails
            declaredField: modifierDetails
            originalField: description
            column: modifier_detalils_description
    manyToOne:
        order:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\Order
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: modifiers
            joinColumns:
                order_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
