WellCommerce\Bundle\OrderBundle\Entity\OrderProduct:
    type: entity
    table: orders_product
    repositoryClass: WellCommerce\Bundle\OrderBundle\Repository\OrderProductRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: AUTO
    embedded:
        netPrice:
            class: WellCommerce\Bundle\CoreBundle\Entity\Price
        grossPrice:
            class: WellCommerce\Bundle\CoreBundle\Entity\Price
    fields:
        quantity:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
        taxValue:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
            column: tax_value
        weight:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
    manyToOne:
        order:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\Order
            fetch: LAZY
            inversedBy: products
            joinColumns:
                order_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        product:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\Product
            fetch: LAZY
            joinColumns:
                product_id:
                    referencedColumnName: id
                    onDelete: RESTRICT
        attribute:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\ProductAttribute
            fetch: LAZY
            joinColumns:
                attribute_id:
                    referencedColumnName: id
                    onDelete: RESTRICT
