WellCommerce\Bundle\OrderBundle\Entity\OrderModifierDetails:
    type: embeddable
    fields:
        name:
            type: string
            length: 255
            nullable: false
        description:
            type: string
            length: 255
            nullable: false
