WellCommerce\CoreBundle\Entity\Meta:
    type: embeddable
    fields:
        title:
            type: string
            length: 255
            nullable: true
        keywords:
            type: text
            nullable: true
        description:
            type: text
            nullable: true
