WellCommerce\SalesBundle\Entity\OrderProduct:
    type: entity
    table: orders_product
    repositoryClass: WellCommerce\SalesBundle\Repository\OrderProductRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    embedded:
        buyPrice:
            class: WellCommerce\CoreBundle\Entity\Price
            columnPrefix: buy_price_
        sellPrice:
            class: WellCommerce\CoreBundle\Entity\Price
            columnPrefix: sell_price_
    fields:
        quantity:
            type: integer
            nullable: false
        weight:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
    manyToOne:
        order:
            targetEntity: WellCommerce\SalesBundle\Entity\Order
            fetch: LAZY
            inversedBy: products
            joinColumns:
                order_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        product:
            targetEntity: WellCommerce\CatalogBundle\Entity\Product
            fetch: LAZY
            joinColumns:
                product_id:
                    referencedColumnName: id
                    onDelete: RESTRICT
        productAttribute:
            targetEntity: WellCommerce\CatalogBundle\Entity\ProductAttribute
            fetch: LAZY
            joinColumns:
                product_attribute_id:
                    referencedColumnName: id
                    onDelete: RESTRICT
