WellCommerce\CmsBundle\Entity\Media:
    type: entity
    table: media
    repositoryClass: WellCommerce\CmsBundle\Repository\MediaRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        path:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        extension:
            type: string
            scale: 0
            length: 12
            unique: false
            nullable: true
            precision: 0
        mime:
            type: string
            scale: 0
            length: 64
            unique: false
            nullable: true
            precision: 0
        size:
            type: string
            scale: 0
            length: 12
            unique: false
            nullable: true
            precision: 0
    oneToMany:
        productPhotos:
            targetEntity: WellCommerce\CatalogBundle\Entity\ProductPhoto
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: photo
            inversedBy: null
            orphanRemoval: true
            orderBy: null
    lifecycleCallbacks:
        prePersist:
            - preUpload
        preUpdate:
            - preUpload
