WellCommerce\CmsBundle\Entity\PageRoute:
    type: entity
    table: route_page
    manyToOne:
        identifier:
            targetEntity: WellCommerce\CmsBundle\Entity\Page
            fetch: LAZY
            joinColumns:
                foreign_id:
                    referencedColumnName: id
                    onDelete: CASCADE
