WellCommerce\CmsBundle\Entity\PageTranslation:
    type: entity
    table: page_translation
    embedded:
        meta:
            class: WellCommerce\CoreBundle\Entity\Meta
    fields:
        name:
            type: string
            length: 255
            nullable: false
        content:
            type: text
        slug:
            type: string
            length: 255
            nullable: false
    oneToOne:
        route:
            targetEntity: WellCommerce\CmsBundle\Entity\PageRoute
            cascade:
                - remove
                - persist
            fetch: LAZY
            joinColumns:
                route_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
