# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    search.layout_box.configurator:
        class: WellCommerce\Bundle\CatalogBundle\Configurator\SearchBoxConfigurator
        tags:
            - { name: layout_box.configurator }
        arguments: [Search, search.layout_box.controller, '@translator.helper']
        calls:
            - [setContainer, ['@service_container']]

    search.result.storage:
        class: WellCommerce\Component\Search\Storage\SearchResultStorage

    search.command.reindex:
        class: WellCommerce\Bundle\CatalogBundle\Command\ReindexCommand
        arguments: ['%locale%']
        tags:
            - { name: console.command }

    search.type.collection:
        class: Doctrine\Common\Collections\ArrayCollection
        public: false

    search.manager:
        class: WellCommerce\Bundle\CatalogBundle\Manager\SearchManager
        arguments: ["@search.type.collection", "@search.result.storage", "@search.adapter"]

    search_request.request_param_converter:
        class: WellCommerce\Bundle\CatalogBundle\Request\ParamConverter\SearchRequestParamConverter
        tags:
            - { name: request.param_converter, converter: search_request, priority: 10 }
        arguments: ['@search.manager']

    search.dataset.front:
        class: WellCommerce\Bundle\CatalogBundle\DataSet\Front\SearchDataSet
        tags:
            - { name: dataset }
        arguments: ['@product.repository','@dataset.manager','@event_dispatcher']
        configurator: ['@dataset.configurator', configure]
        calls:
            - [setContainer, ['@service_container']]

    search.controller.front:
        class: WellCommerce\Bundle\CatalogBundle\Controller\Front\SearchController
        arguments: ['@product.manager']
        calls:
            - [setContainer, ['@service_container']]

    search.layout_box.controller:
        class: WellCommerce\Bundle\CatalogBundle\Controller\Box\SearchBoxController
        arguments: ['@product.manager']
        calls:
            - [setContainer, ['@service_container']]
